-- Story Kiddo Custom Books — story pages on books
--
-- Run after the earlier migrations. Safe to re-run.
-- Adds a JSON array of generated story pages (one string per page).

alter table public.books
  add column if not exists pages jsonb;

comment on column public.books.pages is
  'JSON array of story page strings generated by the Anthropic API.';
comment on table public.books is
  'The generated storybook that belongs to an order. Story text is stored in pages.';
